add update timesheet flow
GarageGroup/internal-timesheet-bot-app pull request #52
Opened 2024-03-07 13:49 UTC by GGSukhorukovEgor

2024-03-11 08:12 UTC, Sauric commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.AwaitDate.cs
> +        activity.ChannelData = JObject.FromObject(CreateChannelDataSelectDate(context.FlowState.Options.UrlWebApp));
Remove `JObject.FromObject`

2024-03-11 08:24 UTC, Sauric commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.AwaitTimesheet.cs
> +partial class TimesheetUpdateFlowStep
Add empty line

2024-03-11 08:25 UTC, Sauric commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.AwaitTimesheet.cs
> +        return (input.Timesheet, input.Cache) switch
Use inline return `=>`

2024-03-11 08:35 UTC, Sauric commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.AwaitTimesheet.cs
> +        if (cache != null)
Use pattern match `if (context.StepState is DateWebAppCacheJson cache)`

2024-03-11 08:44 UTC, Sauric commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.AwaitTimesheet.cs
> +        chatFlow.ForwardValue(crmProjectApi.SelectTimesheet);
Move to next line
``` csharp
=>
chatFlow.ForwardValue(
    crmProjectApi.SelectTimesheet);
```

2024-03-11 08:46 UTC, Sauric commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.AwaitTimesheet.cs
> +    private static async Task<ChatFlowJump<UpdateTimesheetFlowState>> ProcessingMessagesWebApp(
Use `ValueTask` type and remove `async`

2024-03-11 08:47 UTC, Sauric commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.AwaitTimesheet.cs
> +        await AsyncPipeline
Remove await

2024-03-11 08:47 UTC, Sauric commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.AwaitTimesheet.cs
> +            .ToValueTask();
Remove `.ToValueTask()`

2024-03-18 10:41 UTC, Sauric commented on src/endpoint/Timesheet.Delete/FlowStep/Step.AwaitDate.cs
> +        activity.ChannelData = JObject.FromObject(CreateChannelDataSelectDate(context.FlowState.Options.UrlWebApp, daysInterval));
Remove `JObject.FromObject`

2024-03-18 10:41 UTC, Sauric commented on src/endpoint/Timesheet.Delete/FlowStep/Step.AwaitTimesheet.cs
> +                .ToTask()
Use `ToValueTask` instead

2024-03-20 10:27 UTC, pmosk requested changes

2024-03-20 10:27 UTC, pmosk commented on src/endpoint/Timesheet.Update/Flow/FlowState/UpdateTimesheetFlowState.cs
> +    public UpdateTimesheetFlowState(UpdateTimesheetOptions options)
Remove this constructor

2024-03-20 10:27 UTC, pmosk commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.ReadContextData.cs
> +partial class TimesheetUpdateFlowStep
Delete this step

2024-03-20 14:05 UTC, pmosk requested changes

2024-03-20 14:05 UTC, pmosk commented on src/endpoint/Timesheet.Update/Flow/FlowStep/Step.UpdateTimesheet.cs
> +         .Pipe(
Don't use pipeline here

2024-03-20 14:05 UTC, pmosk commented on src/endpoint/Timesheet.Update/Flow/Internal.Json/ProjectCacheJson.cs
> +
remove empty line

2024-03-21 09:55 UTC, pmosk approved these changes

2024-03-21 09:57 UTC, merged